### ISSUE TITLE
Prohibit using @fold inside an @fold scope

### ISSUE THREAD

**Issue by obi1kenobi** [kensho-technologies/graphql-compiler#11]
The code might not enforce this at the moment. Fix it and add a test.

**Comment by obi1kenobi** [comment]
@amartyashankha I think we check for this now, right? Should I close?

**Comment by amartyashankha** [comment]
Yes, we do in https://github.com/kensho-technologies/graphql-compiler/blob/master/graphql_compiler/compiler/directive_helpers.py#L195
