### ISSUE TITLE
Snapshot tests' OrientDB schema is out of sync relative to the test GraphQL schema

### ISSUE THREAD

**Issue by obi1kenobi** [kensho-technologies/graphql-compiler#155]
The current OrientDB schema used for snapshot tests is missing fields and classes that exist in the test GraphQL schema.

Compare:
https://github.com/kensho-technologies/graphql-compiler/blob/c85429d2a56fc5856522429643ce79cce25efda2/graphql_compiler/tests/test_data_tools/schema.sql
vs
https://github.com/kensho-technologies/graphql-compiler/blob/c85429d2a56fc5856522429643ce79cce25efda2/graphql_compiler/tests/test_helpers.py#L86

We should bring them back into sync, and add a test to make sure that they don't diverge again.

**Comment by pmantica1** [comment]
I solved this issue after introducing the automatic schema generation.
