### ISSUE TITLE
GraphQL specification conflict on directive uniqueness per location

### ISSUE THREAD

**Issue by obi1kenobi** [kensho-technologies/graphql-compiler#346]
Just came across this rule in the current version of the GraphQL specification:
https://graphql.github.io/graphql-spec/June2018/#sec-Directives-Are-Unique-Per-Location

We currently allow some directives to appear more than once on a given field (for example, `@filter`). For such situations, the specification has a suggestion to allow the field to be duplicated and have one instance of the directive on each occurrence. As much as I don't like this, we'll have to fall in line with it to remain compliant.

**Comment by bojanserafimov** [comment]
In many places we rely on the assumption that fields are unique (in the macro system selection merging for example). Make sure to address this if we allow duplicate fields.

**Comment by obi1kenobi** [comment]
GraphQL-core v3 allows directives to be marked as `repeatable`, we should definitely do that for `@filter` directives: https://github.com/graphql-python/graphql-core-next/blob/0832f0a73d60e8954f1defb7a397ff02cc7621e4/tests/validation/test_unique_directives_per_location.py

**Comment by pmantica1** [comment]
I think that this issue is solved since we moved to GraphQL-core v3 and added the repeatable directive to filter.
