### ISSUE TITLE
Lack of proper schema serialization function

### ISSUE THREAD

**Issue by pmantica1** [kensho-technologies/graphql-compiler#610]
We currently have a function called `amend_custom_scalar_types` that amends the definition and descriptions of custom scalar types.  We include documentation for it and expose it as public api. However, this function only amends part of the information loss that happens when serializing a GraphQL schema, (we also lose descriptions for everything else). 

We should have two functions that serialize and parse the GraphQL schema info with minimal information loss and expose that as public api.

**Comment by obi1kenobi** [comment]
The part of the issue related to descriptions, directives, and other AST elements lost in the print-parse transformation might be solved by the release of the new GraphQL core library: https://github.com/graphql-python/graphql-core-next/issues/53
