### ISSUE TITLE
get_schema_with_macros() loses scalar type serialization logic

### ISSUE THREAD

**Issue by obi1kenobi** [kensho-technologies/graphql-compiler#661]
Assume the original `macro_registry.schema_without_macros` object has some custom scalar types with their own serialization logic attached, perhaps through a mechanism like https://github.com/kensho-technologies/graphql-compiler#amending-parsed-custom-scalar-types

One would expect that calling `get_schema_with_macros()` on that macro registry would produce a schema with those scalar types' serialization logic preserved. This is unfortunately not what happens — the serialization logic is lost.

We should explicitly copy over all definitions of scalar types from the old schema to the new one to rectify this.

**Comment by pmantica1** [comment]
Fixed when https://github.com/kensho-technologies/graphql-compiler/issues/665 was closed.

**Comment by pmantica1** [comment]
Fixed through https://github.com/kensho-technologies/graphql-compiler/pulls?q=is%3Apr+is%3Aclosed
