### ISSUE TITLE
Amending custom scalar types in the `input_metadata` dict.

### ISSUE THREAD

**Issue by pmantica1** [kensho-technologies/graphql-compiler#665]
During compilation, we rely on the `.serialize` attributes  of `GraphQLScalarType` objects. However, when a GraphQLSchema is serialized and parsed, the `.parse_value`, `.parse_literal` and `.serialize` function definitions of custom scalar types are lost because there is no way to serialize them. That is why we have the `amend_custom_scalar_types` function.  

However, it is both tedious to document what this function does and it is easy for someone to forget to call the `amend_custom_scalar_types` when serializing and parsing the schema. 

Therefore, I think that it would be a good idea to stop relying on the `.serialize` attributes of the input schema to be correctly set. We could simply "fix" them during compilation. Doing so would actually be pretty simple. We would just have to "amend" the `input_metadata` dict in a similar fashion.

**Comment by obi1kenobi** [comment]
> We could simply "fix" them during compilation. Doing so would actually be pretty simple. We would just have to "amend" the input_metadata dict in a similar fashion.

Could you explain your proposed approach in a bit more detail? I'm not sure what you have in mind when you say "fix during compilation".

**Comment by pmantica1** [comment]
So the only place that we use `.parse_value` attributes is in the `insert_arguments_into_query` function. `insert_arguments_into_query` takes in a `CompilationResult` and uses its `input_metadata` attribute to infer the types of the arguments. The `input_metadata` dict uses the `GraphQLScalarType` objects of the schema that was used during compilation. Currently, if a `GraphQLScalarType` object in the schema has an invalid `.parse_value` function then `insert_arguments_into_query` will not work correctly since the `GraphQLScalarType` objects used by `insert_arguments_into_query` are ultimately the ones in the `GraphQLSchema` used for compilation.  

What I am saying is that instead of "amending" the schema, we amend the `input_metadata` dict that is returned by  `_compile_graphql_generic` function.

**Comment by bojanserafimov** [comment]
Why not just hard code the parsing functions into the library, and don't pass them around as a part of some object, but just import them?

**Comment by pmantica1** [comment]
Ok yeah that makes sense. Let's do that.

> Why not just hard code the parsing functions into the library, and don't pass them around as a part of some object, but just import them?
