### ISSUE TITLE
Upgrade to GraphQL-core v3 as soon as it is available; drop Python 2.x support

### ISSUE THREAD

**Issue by obi1kenobi** [kensho-technologies/graphql-compiler#672]
This is a blocker for our 2.0 release:
https://github.com/graphql-python/graphql-core-next/issues/53

**Comment by pmantica1** [comment]
GraphQL-core v3 does not allow for multiple directives in the same field in a query. In other words this query is invalid:
```
{
     ObjectType {
           field @directive1 @directive 
     }
}
```
We need to change tests/documentation/other code to adjust for this change.

**Comment by obi1kenobi** [comment]
In your example, did you mean to make the directives be differently-named, `directive1` and `directive2`? If I understand this correctly, you are saying that a field may only have up to one directive?

**Comment by pmantica1** [comment]
I am just saying that this issue https://github.com/kensho-technologies/graphql-compiler/issues/346
is a blocker. While GraphQL-core does not enforce directive uniqueness peer location, GraphQL-core-next does.

**Comment by obi1kenobi** [comment]
Directives of different names are allowed to be in the same location by the GraphQL spec, see the link in #346. GraphQL-core-next additionally supports repeatable directives, which we should make use of to avoid breaking existing queries: https://github.com/graphql-python/graphql-core-next/blob/0832f0a73d60e8954f1defb7a397ff02cc7621e4/tests/validation/test_unique_directives_per_location.py#L16

**Comment by obi1kenobi** [comment]
GraphQL-core v3 is out: https://github.com/graphql-python/graphql-core-next/releases
