### ISSUE TITLE
Raise errors if unused @tag directives are found

### ISSUE THREAD

**Issue by obi1kenobi** [kensho-technologies/graphql-compiler#8]
Having a `@tag` directive whose value is never used is semantically wrong since the directive could and should simply be removed. This should throw an error, but currently does not.

**Comment by jecdohmann** [comment]
I think this has been fixed - not sure what PR fixed it though

**Comment by obi1kenobi** [comment]
Let's make sure there's a test case for it, and if so I can close the issue.

**Comment by obi1kenobi** [comment]
There's a test case for this in `test_ir_generation_errors.py`.
