### ISSUE TITLE
Upgrade to v2.0 of the Contributor Covenant code of conduct

### ISSUE THREAD

**Issue by obi1kenobi** [kensho-technologies/graphql-compiler#927]
An updated version is available here: https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md

We currently use v1.4, and there are some nice changes and clarifications in v2.0.

**Comment by MichaelaShtilmanMinkin** [comment]
Is there more to this outside of updating `CODE_OF_CONDUCT.rst`?

**Comment by obi1kenobi** [comment]
Should be just that — turning the Markdown version into our `.rst` and plugging in our maintainer contact info in the right places.
