### ISSUE TITLE
Postgres back produces incorrect results for empty fold lists

### ISSUE THREAD

**Issue by chewselene** [kensho-technologies/graphql-compiler#954]
Turning on integrations tests in #953 uncovered a bug. This [db-fiddle](https://www.db-fiddle.com/f/pwwFd8dy46TagLaLjb9RN/0) is modeled after the current output of this [integration test](https://github.com/kensho-technologies/graphql-compiler/blob/main/graphql_compiler/tests/integration_tests/test_backends_integration.py#L764). For `Animal 4`, we expect to see the result `{child_names: []}`, but instead get no results for `Animal 4`.

**Comment by chewselene** [comment]
I think this can be solved with a `LEFT JOIN` from the main selectable to the folded subquery? That is actually what we have written up in #535, but in implementation we used a `JOIN` instead. See this [db-fiddle](https://www.db-fiddle.com/f/pwwFd8dy46TagLaLjb9RN/1). If so, the fix is a super easy change [here](https://github.com/kensho-technologies/graphql-compiler/blob/089653080e68decadd7a86b201a1cabfc7be2dc5/graphql_compiler/compiler/emit_sql.py#L1168)! @bojanserafimov @obi1kenobi let me know what you think!

**Comment by obi1kenobi** [comment]
Looks good to me! Let's go for it 🙌
